sudo: required
language: C++
os:
  - linux
  - osx
services:
  - docker
compiler:
  - gcc
  - clang

before_install:
  - echo $DEPLOY_KEY_ENC | base64 --decode | openssl aes-256-cbc -K $encrypted_83a41ac424a6_key -iv $encrypted_83a41ac424a6_iv -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker build -f Dockerfile -t strawberry-build .;
      docker run --name build -itd strawberry-build /bin/bash;
      docker exec build git clone https://github.com/jonaski/strawberry;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      git fetch --unshallow;
      git pull;
      brew update;
      brew unlink python;
      brew install glib pkgconfig protobuf protobuf-c qt;
      brew install sqlite --with-fts;
      brew install gstreamer gst-plugins-base;
      brew install gst-plugins-good --with-flac;
      brew install gst-plugins-bad gst-plugins-ugly gst-libav;
      brew install chromaprint;
      brew install libcdio libmtp libimobiledevice libplist;
      export Qt5_DIR=/usr/local/opt/qt5/lib/cmake;
      ls /usr/local/lib/gstreamer-1.0
    fi
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker exec build cmake -Hstrawberry -Bbuild -DENABLE_STREAM_DEEZER=ON ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir build; cd build; cmake .. -DUSE_BUNDLE=ON -DENABLE_STREAM_DEEZER=ON ; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker exec build make -C build -j8 ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      make -j8;
      sudo make install;
      sudo ../dist/macos/macdeploy.py strawberry.app;
      ../dist/macos/create-dmg.sh strawberry.app;
  fi
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ls -lh strawberry.dmg; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then rsync -e "ssh -o StrictHostKeyChecking=no" -va strawberry*.dmg travis@echoes.jkvinge.net:/home/travis/builds/macos; fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
  
